2021-02-22 11:36:03.817 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 11:37:07.094 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 11:38:18.895 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 11:39:09.015 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 14:00:28.924 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 15:04:38.353 +03:00 [Error] {"ExceptionMessage":"Yetkiniz Yok","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"GetAll","User":"?","Parameters":[]}
2021-02-22 16:11:37.656 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"İstanbul d","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T14:11:42.4427109","CreatedBy":"Mustafa Fındık","ModifiedBy":null,"ModifiedDate":"2021-02-22T16:11:37.4954304+03:00"},"Type":"City"}]}
2021-02-22 16:12:11.176 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"İstanbul","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T14:11:42.4427109","CreatedBy":"Mustafa Fındık","ModifiedBy":null,"ModifiedDate":"2021-02-22T16:12:11.0521149+03:00"},"Type":"City"}]}
2021-02-22 16:22:12.544 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"İstanbul g","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T14:11:42.4427109","CreatedBy":"Mustafa Fındık","ModifiedBy":"Mustafa Fındık","ModifiedDate":"2021-02-22T14:11:42.4427153"},"Type":"City"}]}
2021-02-22 16:27:25.122 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"İstanbul","Warehouses":null,"Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"2021-02-22T16:27:24.9608345+03:00"},"Type":"City"}]}
2021-02-22 16:28:33.321 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"İstanbul","Warehouses":null,"Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:29:19.528 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string e","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:28:56.288Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:28:56.288Z"},"Type":"City"}]}
2021-02-22 16:30:50.159 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:30:02.114Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:30:02.114Z"},"Type":"City"}]}
2021-02-22 16:31:55.387 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:30:02.114Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:30:02.114Z"},"Type":"City"}]}
2021-02-22 16:32:18.789 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:30:02.114Z","CreatedBy":"string","ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:32:27.615 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:30:02.114Z","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:32:35.120 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:32:48.214 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"string","Warehouses":null,"Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:33:06.683 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"56565","Warehouses":null,"Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"City"}]}
2021-02-22 16:36:08.925 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"SD","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:36:13.464 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"SD","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:36:17.311 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"SD","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:36:23.223 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"56565","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:36:27.572 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"456464646","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:36:53.530 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"456464646","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:35:47.563Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:35:47.563Z"},"Type":"City"}]}
2021-02-22 16:43:55.079 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"23","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:43:38.655Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:43:38.655Z"},"Type":"City"}]}
2021-02-22 16:45:56.501 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"SD","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:45:39.66Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:45:39.66Z"},"Type":"City"}]}
2021-02-22 16:48:42.344 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"23","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:48:04.577Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:48:04.577Z"},"Type":"City"}]}
2021-02-22 16:55:20.934 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"32","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:54:56.254Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:54:56.254Z"},"Type":"City"}]}
2021-02-22 16:55:50.115 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"city","Value":{"CityName":"Adana","Warehouses":null,"Id":11,"CreateDate":"2021-02-22T13:54:56.254","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:54:56.254"},"Type":"City"}]}
2021-02-22 16:59:36.905 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"4","Id":11,"CreateDate":"2021-02-22T13:59:13.308Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T13:59:13.308Z"},"Type":"CityDto"}]}
2021-02-22 17:02:04.188 +03:00 [Error] {"ExceptionMessage":"Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":0,"CreateDate":"2021-02-22T14:01:56.269Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:01:56.269Z"},"Type":"CityDto"}]}
2021-02-22 17:02:21.754 +03:00 [Error] {"ExceptionMessage":"Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T14:01:56.269Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:01:56.269Z"},"Type":"CityDto"}]}
2021-02-22 17:03:00.093 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T14:01:56.269Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:01:56.269Z"},"Type":"CityDto"}]}
2021-02-22 17:07:34.151 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"23","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:15:03.785 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"st3ring","Id":11,"CreateDate":"2021-02-22T14:14:49.473Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:14:49.473Z"},"Type":"CityDto"}]}
2021-02-22 17:16:21.360 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"2323","Id":11,"CreateDate":"2021-02-22T14:16:07.626Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:16:07.626Z"},"Type":"CityDto"}]}
2021-02-22 17:21:09.102 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"233","Id":11,"CreateDate":"2021-02-22T14:20:52.115Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:20:52.115Z"},"Type":"CityDto"}]}
2021-02-22 17:24:27.597 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"st25ring","Id":11,"CreateDate":"2021-02-22T14:24:19.392Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:24:19.392Z"},"Type":"CityDto"}]}
2021-02-22 17:28:44.646 +03:00 [Error] {"ExceptionMessage":"Object reference not set to an instance of an object.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"23","Id":1,"CreateDate":"2021-02-22T14:28:25.628Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:28:25.628Z"},"Type":"CityDto"}]}
2021-02-22 17:29:14.488 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"str2i2ng","Id":11,"CreateDate":"2021-02-22T14:29:03.18Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:29:03.18Z"},"Type":"CityDto"}]}
2021-02-22 17:30:11.020 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"343","Id":11,"CreateDate":"2021-02-22T14:24:19.392","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:24:19.392"},"Type":"CityDto"}]}
2021-02-22 17:30:15.618 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"stri2ng4","Id":11,"CreateDate":"2021-02-22T14:24:19.392","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:24:19.392"},"Type":"CityDto"}]}
2021-02-22 17:39:48.501 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:39:50.272 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:41:58.862 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:44:16.065 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T14:44:12.398Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T14:44:12.398Z"},"Type":"CityDto"}]}
2021-02-22 17:46:02.296 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:46:37.566 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:46:39.149 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:46:40.532 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:48:20.708 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 17:49:09.592 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"3r3543","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 18:38:14.035 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"2323","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 18:49:38.548 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 18:50:31.096 +03:00 [Error] {"ExceptionMessage":"The instance of entity type 'City' cannot be tracked because another instance with the key value '{Id: 11}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 18:51:19.731 +03:00 [Error] {"ExceptionMessage":"Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"0001-01-01T00:00:00","CreatedBy":null,"ModifiedBy":null,"ModifiedDate":"0001-01-01T00:00:00"},"Type":"CityDto"}]}
2021-02-22 18:51:51.250 +03:00 [Error] {"ExceptionMessage":"Value cannot be null. (Parameter 'entity')","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T15:51:45.521Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T15:51:45.521Z"},"Type":"CityDto"}]}
2021-02-22 18:52:46.566 +03:00 [Error] {"ExceptionMessage":"Value cannot be null. (Parameter 'entity')","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T15:52:41.305Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T15:52:41.305Z"},"Type":"CityDto"}]}
2021-02-22 18:54:15.824 +03:00 [Error] {"ExceptionMessage":"Value cannot be null. (Parameter 'entity')","FullName":"StockManagement.Business.Abstract.ICityService","MethodName":"Update","User":"?","Parameters":[{"Name":"cityDto","Value":{"CityName":"string","Id":11,"CreateDate":"2021-02-22T15:53:25.599Z","CreatedBy":"string","ModifiedBy":"string","ModifiedDate":"2021-02-22T15:53:25.599Z"},"Type":"CityDto"}]}
